#!/bin/bash
#for dataType in rawMid raw filtered
#do
#    for i in {0..23} # 1 2
#    do
#        t=$(printf "%02d" $i)
#        python ~/kode/simraStudies/Sula/convertCoords.py --originx -200 --originy 6899800 --date="2020-11-19 "$t":00" --measurementfolder="measurements/"$dataType --resultsfolder="measurements/"$dataType
#    done
#done

#rename -v 's/simM1Sula_//' *
for f in *
do
    cd f
    cp ../../simra.in .
    for i in {0..8} # 1 2
    do
        for M in 1 
        do
            cp contM${M}Sula.res_00+$i temp.res
            siso -f vts temp.res M${M}_$i.vts --in-endianness big --mesh $HOME/results/simra/Sula/met_new/M${M}/mesh_M${M}.dat 
        done

    done
    rm temp.res
    cd ..
done

#year=2020
#month=11
#wget https://thredds.met.no/thredds/fileServer/obs/mast-svv-e39/$year/$month/${year}${month}_Traelboneset_10hz.nc ~/results/simra/Sula/measurements/
